<?php

function event_menu() {
  $items = array();
  $items['event/form'] = array(
    'title' => 'My form',
    'page callback' => 'event_callback',
    'access arguments' => array('access content'),
    'description' => 'My form',
    'type' => MENU_CALLBACK,
    'file' => 'event.inc',
  );

  $items['event/result'] = array(
    'title' => 'result page',
    'page callback' => 'event_result_callback',
    'access arguments' => array('access content'),
    'description' => 'My form',
    'type' => MENU_CALLBACK,
    'file' => 'event.inc',
  );
  return $items;
}


